### ISSUE TITLE
example5 raising exception for wrong typed arguments.

### ISSUE THREAD

**Issue by alexge233** [taichi-dev/voxel-challenge#31]
https://github.com/taichi-dev/voxel-challenge/blob/8f5b6fbf6d11151326a185fa45bfc604194789bf/example5.py#L42

Hi,

Python 3.9 running on Ubuntu 18.04 with CUDA/Vulkan backend.
Example5 throws an exception:

```
Traceback (most recent call last):
  File "example5.py", line 64, in <module>
    initialize_voxels()
  File "venv/lib/python3.9/site-packages/taichi/lang/kernel_impl.py", line 917, in wrapped
    raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiTypeError:
On line 54 of file "example5.py", in initialize_voxels:
    make_cloud_city(base, n)
    ^^^^^^^^^^^^^^^^^^^^^^^^
On line 42 of file "example5.py", in make_cloud_city:
        for k in ti.ndrange((-height*.6+base, height*1.2+base)):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Every argument of ndrange should be an integer scalar or a tuple/list of (int, int)
```

Casting the tuple to int 8 seems to fix it:

```
lims = (ti.cast(-height*.6+base, ti.i8), ti.cast(height*1.2+base, ti.i8))
for k in ti.ndrange(lims):
```

Also, all examples raise this error, but it doesn't seem to stop the other examples from running:

```
GLFW Error 65537: The GLFW library is not initialized
```

**Comment by neozhaoliang** [comment]
@alexge233 I think this is because `ti.ndrange` function is changed after v1.0. It does not accept float args anymore. Just fixed that. Thanks!
